name: test 7z

on: [push]

jobs:
  build_asset_windows:
    name: Build asset on Windows
    runs-on: windows-2019
    steps:
      - name: install 7z
        run: choco install 7zip.portable
      - name: Run 7z
        run: 7z
