name: Build asset on macOS

on: [push]

jobs:
  build_asset_mac:
    name: Upload Asset on macOS (+ iOS)
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependency
        run: brew install coreutils automake

      - name: Run Buildscript
        run: sh ./build-on-mac-ios.sh