name: Build asset on macOS

on: [push]

jobs:
  build_asset_linux:
    name: Build asset on macOS
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependency
        run: brew install coreutils automake

      - name: Run Buildscript
        run: sh ./build-on-mac-silicon.sh || cat sqlcipher/config.log

